#!/usr/bin/env bash
set -euo pipefail

# Astro's sitemap integration writes into dist/ during build.
npm run build

if [ ! -f dist/sitemap-index.xml ]; then
  echo "Expected dist/sitemap-index.xml was not generated." >&2
  exit 1
fi

echo "Sitemap generated by Astro at dist/sitemap-index.xml"
